version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4

# Common anchors
only_master_branch: &only_master_branch
  filters:
    branches:
      only:
        - master

workflows:
  version: 2

  check_and_publish_dev:
    jobs:
      - orb-tools/lint

      # Gradle publish
      - orb-tools/pack:
          name: Pack gradle-publish
          source-dir: gradle-publish/
          destination-orb-path: gradle-publish-orb.yml
          workspace-path: gradle-publish-orb.yml
          artifact-path: gradle-publish-orb.yml
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          name: Publish gradle-publish dev release
          orb-name: freeletics/gradle-publish
          orb-path: workspace/gradle-publish-orb.yml
          requires:
            - "Pack gradle-publish"
      - "Gradle-publish patch release":
          type: approval
          requires:
            - "Publish gradle-publish dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish gradle-publish patch release"
          orb-name: freeletics/gradle-publish
          release: patch
          publish-version-tag: false
          requires:
            - "Gradle-publish patch release"
      - "Gradle-publish minor release":
          type: approval
          requires:
            - "Publish gradle-publish dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish gradle-publish minor release"
          orb-name: freeletics/gradle-publish
          release: minor
          publish-version-tag: false
          requires:
            - "Gradle-publish minor release"
      - "Gradle-publish major release":
          type: approval
          requires:
            - "Publish gradle-publish dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish gradle-publish major release"
          orb-name: freeletics/gradle-publish
          release: major
          publish-version-tag: false
          requires:
            - "Gradle-publish major release"

      # Prepare mobile workflow
      - orb-tools/pack:
          name: Pack prepare-mobile-workflow
          source-dir: prepare-mobile-workflow/
          destination-orb-path: prepare-mobile-workflow-orb.yml
          workspace-path: prepare-mobile-workflow-orb.yml
          artifact-path: prepare-mobile-workflow-orb.yml
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          name: Publish prepare-mobile-workflow dev release
          orb-name: freeletics/prepare-mobile-workflow
          orb-path: workspace/prepare-mobile-workflow-orb.yml
          requires:
            - "Pack prepare-mobile-workflow"
      - "Prepare-mobile-workflow patch release":
          type: approval
          requires:
            - "Publish prepare-mobile-workflow dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish prepare-mobile-workflow patch release"
          orb-name: freeletics/prepare-mobile-workflow
          publish-version-tag: false
          release: patch
          requires:
            - "Prepare-mobile-workflow patch release"
      - "Prepare-mobile-workflow minor release":
          type: approval
          requires:
            - "Publish prepare-mobile-workflow dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish prepare-mobile-workflow minor release"
          orb-name: freeletics/prepare-mobile-workflow
          publish-version-tag: false
          release: minor
          requires:
            - "Prepare-mobile-workflow minor release"
      - "Prepare-mobile-workflow major release":
          type: approval
          requires:
            - "Publish prepare-mobile-workflow dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish prepare-mobile-workflow major release"
          orb-name: freeletics/prepare-mobile-workflow
          publish-version-tag: false
          release: major
          requires:
            - "Prepare-mobile-workflow major release"

      # Firebase test lab
      - orb-tools/pack:
          name: Pack firebase-testlab
          source-dir: firebase-testlab/
          destination-orb-path: firebase-testlab-orb.yml
          workspace-path: firebase-testlab-orb.yml
          artifact-path: firebase-testlab-orb.yml
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          name: Publish firebase-testlab dev release
          orb-name: freeletics/firebase-testlab
          orb-path: workspace/firebase-testlab-orb.yml
          requires:
            - "Pack firebase-testlab"
      - "Firebase-testlab patch release":
          type: approval
          requires:
            - "Publish firebase-testlab dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish firebase-testlab patch release"
          orb-name: freeletics/firebase-testlab
          publish-version-tag: false
          release: patch
          requires:
            - "Firebase-testlab patch release"
      - "Firebase-testlab minor release":
          type: approval
          requires:
            - "Publish firebase-testlab dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish firebase-testlab minor release"
          orb-name: freeletics/firebase-testlab
          publish-version-tag: false
          release: minor
          requires:
            - "Firebase-testlab minor release"
      - "Firebase-testlab major release":
          type: approval
          requires:
            - "Publish firebase-testlab dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish firebase-testlab major release"
          orb-name: freeletics/firebase-testlab
          publish-version-tag: false
          release: major
          requires:
            - "Firebase-testlab major release"

      # Kaniko Publish
      - orb-tools/pack:
          name: Pack kaniko-publish
          source-dir: kaniko-publish/
          destination-orb-path: orb.yml
          workspace-path: orb.yml
          artifact-path: orb.yml
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          name: Publish kaniko-publish dev release
          orb-name: freeletics/kaniko-publish
          orb-path: workspace/orb.yml
          requires:
            - "Pack kaniko-publish"
      - "kaniko-publish patch release":
          type: approval
          requires:
            - "Publish kaniko-publish dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish kaniko-publish patch release"
          orb-name: freeletics/kaniko-publish
          publish-version-tag: false
          release: patch
          requires:
            - "kaniko-publish patch release"
      - "kaniko-publish minor release":
          type: approval
          requires:
            - "Publish kaniko-publish dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish kaniko-publish minor release"
          orb-name: freeletics/kaniko-publish
          publish-version-tag: false
          release: minor
          requires:
            - "kaniko-publish minor release"
      - "kaniko-publish major release":
          type: approval
          requires:
            - "Publish kaniko-publish dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish kaniko-publish major release"
          orb-name: freeletics/kaniko-publish
          publish-version-tag: false
          release: major
          requires:
            - "kaniko-publish major release"

      # Privacy Sync
      - orb-tools/pack:
          name: Pack privacy-sync
          source-dir: privacy-sync/
          destination-orb-path: orb.yml
          workspace-path: orb.yml
          artifact-path: orb.yml
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          name: Publish privacy-sync dev release
          orb-name: freeletics/privacy-sync
          orb-path: workspace/orb.yml
          requires:
            - "Pack privacy-sync"
      - "privacy-sync patch release":
          type: approval
          requires:
            - "Publish privacy-sync dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish privacy-sync patch release"
          orb-name: freeletics/privacy-sync
          publish-version-tag: false
          release: patch
          requires:
            - "privacy-sync patch release"
      - "privacy-sync minor release":
          type: approval
          requires:
            - "Publish privacy-sync dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish privacy-sync minor release"
          orb-name: freeletics/privacy-sync
          publish-version-tag: false
          release: minor
          requires:
            - "privacy-sync minor release"
      - "privacy-sync major release":
          type: approval
          requires:
            - "Publish privacy-sync dev release"
          <<: *only_master_branch
      - orb-tools/dev-promote-prod:
          name: "Publish privacy-sync major release"
          orb-name: freeletics/privacy-sync
          publish-version-tag: false
          release: major
          requires:
            - "privacy-sync major release"
